name: API Extractor
on:
  push:
    branches:
      - "main"
    paths:
      - "docs/api/*.md"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v3
      - id: changed_docs_files
        name: Changed Docs Files
        uses: tj-actions/changed-files@v35
        with:
          files: docs/api/**/*.md
          json: true
      - id: setup-deno
        name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.30.x
      - id: sync-changes
        name: Sync Changes to Main Docs Repository
        # if: ${{ steps.changed_docs_files.outputs.any_changed == true || steps.changed_docs_files.outputs.any_deleted == true }}
        run: |
          deno run --allow-env --allow-net --unstable https://raw.githubusercontent.com/nizelabs/aedoc/main/scripts/actions/dispatch-api-sync-workflow.ts \
            --changed "${{ steps.changed_docs_files.outputs.all_changed_files }}" --deleted "${{ steps.changed_docs_files.outputs.deleted_files }}" \
            --branch main --pat "${{ secrets.PAT_DOCS }}"
